# default
H_3D: 136
W_3D: 240
D_3D: 316
Q: 0.31746031746031744
LR: 0.0001
HALF_IMAGES: 1
EPOCHS: 999
DET_TH: 0.4
NMS_TH: 0.1
N_WORKERS: 1
BATCH_SIZE: 1
DEVICE: 'cuda:0'
EPOCH_LEN: 1
TEST_SET_LEN: 1
MOTSYNTH_PATH: 'Z:/Datasets/MOTSynth'
